"""
Pacote de configurações do sistema
"""
from .theme import (
    COR_PRIMARY,
    COR_SECONDARY,
    COR_INFO,
    ICONE_ADICIONAR,
    ICONE_EDITAR,
    ICONE_EXCLUIR,
    MSG_SUCESSO_ADICIONAR,
    MSG_SUCESSO_ATUALIZAR,
    MSG_SUCESSO_EXCLUIR,
    OPCOES_REGISTROS_POR_PAGINA,
    REGISTROS_POR_PAGINA_DEFAULT
)

__all__ = [
    'COR_PRIMARY',
    'COR_SECONDARY',
    'COR_INFO',
    'ICONE_ADICIONAR',
    'ICONE_EDITAR',
    'ICONE_EXCLUIR',
    'MSG_SUCESSO_ADICIONAR',
    'MSG_SUCESSO_ATUALIZAR',
    'MSG_SUCESSO_EXCLUIR',
    'OPCOES_REGISTROS_POR_PAGINA',
    'REGISTROS_POR_PAGINA_DEFAULT'
]
